apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-provider
  template:
    metadata:
      labels:
        app: data-provider
    spec:
      containers:
        - name: data-provider
          image: hashicorp/http-echo
          args: ["-text=Hello from data provider"]
          ports:
            - containerPort: 5678
