apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tractusx-umbrella
  namespace: argocd
spec:
  project: default
  source:
    path: helm/umbrella
    repoURL: https://github.com/aminshuvo/tractusx-edc-project.git
    targetRevision: master
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tractusx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true